# https://www.thadaw.com/posts/publishing-docker-image-on-git-hub-package-publicly-with-github-actions-6wrk7rh/
# https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages
name: Deploy
run-name: Deploy from ${{ inputs.repository }}[${{ inputs.branch }}][${{ inputs.image_name }}] by @${{ github.actor }}
# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  workflow_dispatch:
    inputs:
      repository:
        description: "Repository"
        required: true
        default: "T-T-Software-Solution/ttss-fe-mono"
      branch:
        description: "Branch"
        required: true
        default: "main"
      image_name:
        description: "Image Name"
        required: true
        default: "ttss/backoffice"
      image_tag:
        description: "Image Tag"
        required: true
        default: "test-2024-01-24"
      working_dir:
        description: "Working Directory"
        required: true
        default: "."
      build_args:
        description: "Build Arguments, JSON format, type: Record<string, string>"
        required: true
        default: "{ \"PROJECT_DIR\": \"apps/backoffice\" }"
      dockerfile:
        description: "Dockerfile"
        required: true
        default: "./apps/backoffice/Dockerfile"

# Defines two custom environment variables for the workflow. These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
# env:
#   container_registry_server: ${{ secrets.ACR_SERVER_NAME }}.azurecr.io
#   container_registry_username: ${{ secrets.ACR_SERVER_NAME }}
#   container_registry_password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  build-and-push-image:
    name: "🚀 Deploy"
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Build Composite
        uses: actions/checkout@v4
        with:
          path: composite-actions

      - name: Call Composite build and publish docker image
        uses: ./composite-actions/.github/workflows/composite/build-and-publish-docker-image
        with:
          secrets: ${{ toJson(secrets) }}
          gh_token: ${{ secrets.GH_TOKEN_ORG_LEVEL_READ_WRITE_THADA_TTSS }}
          container_registry_server: ${{ secrets.ACR_SERVER_NAME }}.azurecr.io
          container_registry_username: ${{ secrets.ACR_SERVER_NAME }}
          container_registry_password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
          repository: ${{ inputs.repository }}
          branch: ${{ inputs.branch }}
          image_name: ${{ inputs.image_name }}
          image_tag: ${{ inputs.image_tag }}
          working_dir: ${{ inputs.working_dir }}
          build_args: ${{ inputs.build_args }}
          dockerfile: ${{ inputs.dockerfile }}

